### ISSUE TITLE
Custom folder to look for controllers

### ISSUE THREAD

**Issue by psantos10** [dannyvankooten/PHP-Router#125]
How can I set the folder where the router must look for the controllers? 

at this moment my controllers are at `app/controllers`. To get it work I am doing:

```yml
base_path: /

routes:
  index: [/, app\controllers\PagesController.index, GET]
```

I want to do the following:

```yml
base_path: /

routes:
  index: [/, PagesController.index, GET]
```

and by default to search the "PagesController" class to the specific folder like `app\controllers`

Thank you!
