### ISSUE TITLE
Ability to create routes from yaml files

### ISSUE THREAD

**Issue by malukenho** [dannyvankooten/PHP-Router#25]
With this, we can centralize the routing settings for our project created as **_PHPRouter**_. Besides providing us greater flexibility and mobility between exchange routes, classes, methods and verbs.

**_Here is my proposal:**_ _The `yaml` files should describe the necessary class work without the need for further settings._

I **SUGGEST** the following syntax for the yaml files:

``` yaml
- base_path: /blog

- routes:
  - index:
     - [/, someClass.indexAction, GET]
  - contact:
     - [/contact, someClass.contactAction, GET]
  - about:
     - [/about, someClass.aboutAction, GET]
```

In our frontController, we would have something **SIMILAR** to this:

``` php
<?php
require __DIR__.'/vendor/autoload.php';

use PHPRouter\Config;
use PHPRouter\Router;

$config = Config::loadFromFile('routes.yaml');
$router = Router::parseConfig($config);
$request = $route->matchCurrentRequest();

var_dump($request);
```

What do you think about this?
